// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteSearchQueryWrapper(arg1) {
  return window['go']['main']['App']['ExecuteSearchQueryWrapper'](arg1);
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GoBackward() {
  return window['go']['main']['App']['GoBackward']();
}

export function GoForward() {
  return window['go']['main']['App']['GoForward']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PushToHistory(arg1) {
  return window['go']['main']['App']['PushToHistory'](arg1);
}
