// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
<<<<<<< HEAD

export function GetCurrentDirectory():Promise<string>;

export function GetFiles(arg1:string):Promise<Array<main.File>>;
=======
>>>>>>> ankitpatel

export function GetCurrentDirectory():Promise<string>;

export function GetFiles(arg1:string):Promise<Array<main.CustomFile>>;

export function GoBackward():Promise<string>;

export function GoForward():Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function PushToHistory(arg1:string):Promise<void>;
