// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewFile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFile'](arg1, arg2);
}

export function CreateNewFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFolder'](arg1, arg2);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function ExecuteSearchQueryWrapper(arg1) {
  return window['go']['main']['App']['ExecuteSearchQueryWrapper'](arg1);
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function GoBackward() {
  return window['go']['main']['App']['GoBackward']();
}

export function GoForward() {
  return window['go']['main']['App']['GoForward']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PushToHistory(arg1) {
  return window['go']['main']['App']['PushToHistory'](arg1);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}
